### ISSUE TITLE
max()

### ISSUE THREAD

**Issue by personman** [TheSoftwareFarm/exprlib#1]
I'm interested in writing an equation like this: 

```
max({{variable_one}}, {{variable_two}}, {{variable_three}})
```

Assuming your variables were 8, 9, 10, this would return 10. Do you think that would be useful? If I worked on it and sent a pull request, would you want it?

**Comment by dragosperca** [comment]
i'll have a look on your pull request tomorrow morning and run some tests, but it looks good, thank you!

PS: we only forked the code from elsewhere, the library wasn't maintained anymore and we needed it

**Comment by personman** [comment]
Thanks for taking a look. I was using the prior version of exprlib and when they discontinued it I decided I needed to create a fork. But in the process of submitting it to Packagist, they flagged your fork as a possible duplicate. So, I just used yours. Thanks for maintaining it!
