### ISSUE TITLE
Multiple avg(), max(), etc. in equation doesn't work

### ISSUE THREAD

**Issue by personman** [TheSoftwareFarm/exprlib#3]
An equation like this isn't working:

```
avg(3, 4, 5) + avg(7, 8, 9)
```

The result should be 12 (4 + 8), but instead the result is just 8. The first avg() isn't getting processed. I'm looking into it, but I wanted to alert you guys in case you know of a good fix. Thanks

**Comment by personman** [comment]
I found the answer! Each Scope subclass like Max, Avg, etc., needs to extend ScopeGroup rather than Scope. Pull request coming soon.

**Comment by personman** [comment]
I added pull request #4.

**Comment by dragosperca** [comment]
this seems to have done the trick!
